# Map display specific overrides
# Only include values you want to override from base config

default_view:
  zoom_start: 8
  center_lat: 55.12
  center_lon: 14.92
  tiles: "OpenStreetMap" # Options: OpenStreetMap, CartoDB positron, CartoDB dark_matter

flow_layer:
  region_labels:
    enabled: false           
    font_size: "12px"       
    font_weight: "bold"     
    color: "#333"           
    offset_y: -25           
