special_regions:
  Global Market:
    lat: 55.511515
    lon: 15.987998
  
# These regions in Bornholm need to be hardcoded to appear correctly on the map,
# or else they map to somewhere in Germany and Switzerland due to a similar name.
  HASLE: 
    lat: 55.183333
    lon: 14.705

  NEXOE:
    lat: 55.062500
    lon: 15.131944