{{- if .Values.customIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "speedlocal-streamlit.fullname" . }}-multi-app
  labels:
    {{- include "speedlocal-streamlit.labels" . | nindent 4 }}
  annotations:
    # NGINX Inc controller annotations for Streamlit WebSocket support
    nginx.org/proxy-buffering: "false"
    nginx.org/proxy-read-timeout: "3600s"
    nginx.org/proxy-send-timeout: "3600s"
    nginx.org/proxy-connect-timeout: "60s"
    nginx.org/client-max-body-size: "50m"
    # WebSocket support for all Streamlit services
    nginx.org/websocket-services: "times-app,flow-maps-app,sankey-app,database-app"
    # Sticky sessions for each path
    nginx.org/sticky-cookie-services: |
      times-app route expires=1h path=/times
      flow-maps-app route expires=1h path=/flowmaps  
      sankey-app route expires=1h path=/sankey
      database-app route expires=1h path=/database
    # Path rewriting to remove app prefixes
    nginx.org/rewrites: |
      serviceName=times-app rewrite=/times/(.*) /$1;
      serviceName=flow-maps-app rewrite=/flowmaps/(.*) /$1;
      serviceName=sankey-app rewrite=/sankey/(.*) /$1;
      serviceName=database-app rewrite=/database/(.*) /$1;
    {{- with .Values.customIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.customIngress.tls }}
  tls:
    {{- range .Values.customIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.customIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        # Root path - could serve a landing page or redirect
        - path: /
          pathType: Prefix
          backend:
            service:
              name: times-app
              port:
                number: 8501
        # TIMES Data Explorer
        - path: /times
          pathType: Prefix
          backend:
            service:
              name: times-app
              port:
                number: 8501
        # Energy Flow Maps  
        - path: /flowmaps
          pathType: Prefix
          backend:
            service:
              name: flow-maps-app
              port:
                number: 8501
        # Sankey Diagrams
        - path: /sankey
          pathType: Prefix
          backend:
            service:
              name: sankey-app
              port:
                number: 8501
        # Database Tools
        - path: /database
          pathType: Prefix
          backend:
            service:
              name: database-app
              port:
                number: 8501
        # Streamlit internal resources - route to all apps
        - path: /_stcore
          pathType: Prefix
          backend:
            service:
              name: times-app
              port:
                number: 8501
        - path: /static
          pathType: Prefix  
          backend:
            service:
              name: times-app
              port:
                number: 8501
        - path: /healthz
          pathType: Prefix
          backend:
            service:
              name: times-app
              port:
                number: 8501
    {{- end }}
{{- end }}