name: Release Please

on:
  push:
    branches: [ main ]
    paths:
      - 'streamlit-app/**'
      - '.github/workflows/release-please-config.json'
      - '.github/workflows/release-please-manifest.json'
      - '.github/workflows/release-please.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/workflows/release-please-config.json
          manifest-file: .github/workflows/release-please-manifest.json

