name: Streamlit Build & Deploy (on Release)

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Image/helm tag to use (e.g. v1.2.3)"
        required: true

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 305363105399
  IMAGE_REPO: speedlocal/streamlit-app
  SERVICE_KEY: speedlocalStreamlit
  PROD_VALUES: helm-chart/configuration/production.yaml

jobs:
  release-streamlit:
    name: Build image and update production Helm values
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::305363105399:role/ECRGithubManager
          aws-region: eu-west-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names $IMAGE_REPO >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name $IMAGE_REPO

      - name: Resolve tag (release or manual)
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_REF_NAME: ${{ github.event.release.tag_name }}

      - name: Build image
        run: |
          REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          docker build -t $REGISTRY/$IMAGE_REPO:${{ steps.tag.outputs.tag }} streamlit-app

      - name: Push image
        run: |
          REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          docker push $REGISTRY/$IMAGE_REPO:${{ steps.tag.outputs.tag }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update production Helm values with new tag
        run: |
          set -euo pipefail
          yq -i \
            '."flowcore-microservices".deployments."'"$SERVICE_KEY"'".deployment.tag = "'"${{ steps.tag.outputs.tag }}"'"' \
            $PROD_VALUES
          echo "Updated $PROD_VALUES to tag ${{ steps.tag.outputs.tag }}"

      - name: Commit Helm change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix(helm): :rocket: Update prod tag to ${{ steps.tag.outputs.tag }}"
          file_pattern: ${{ env.PROD_VALUES }}



